// Mocks generated by Mockito 5.4.6 from annotations
// in lunchbox/test/features/product/providers/product_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fpdart/fpdart.dart' as _i3;
import 'package:lunchbox/core/errors/errors.dart' as _i4;
import 'package:lunchbox/features/product/entities/product_model.dart' as _i5;
import 'package:lunchbox/features/product/repositories/product_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getProductsByDeviceId(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByDeviceId, [deviceId]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(this, Invocation.method(#getProductsByDeviceId, [deviceId])),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, _i5.ProductModel> getProductById(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i6
                .dummyValue<_i3.TaskEither<_i4.Failure, _i5.ProductModel>>(
                  this,
                  Invocation.method(#getProductById, [productId]),
                ),
          )
          as _i3.TaskEither<_i4.Failure, _i5.ProductModel>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getAvailableProducts(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableProducts, [deviceId]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(this, Invocation.method(#getAvailableProducts, [deviceId])),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getDiscountProducts(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscountProducts, [deviceId]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(this, Invocation.method(#getDiscountProducts, [deviceId])),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getProductsByCategory(
    String? deviceId,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByCategory, [deviceId, category]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(
                  this,
                  Invocation.method(#getProductsByCategory, [
                    deviceId,
                    category,
                  ]),
                ),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, List<String>> getProductCategories(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductCategories, [deviceId]),
            returnValue: _i6
                .dummyValue<_i3.TaskEither<_i4.Failure, List<String>>>(
                  this,
                  Invocation.method(#getProductCategories, [deviceId]),
                ),
          )
          as _i3.TaskEither<_i4.Failure, List<String>>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> searchProducts(
    String? deviceId,
    String? keyword, {
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchProducts,
              [deviceId, keyword],
              {#category: category},
            ),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(
                  this,
                  Invocation.method(
                    #searchProducts,
                    [deviceId, keyword],
                    {#category: category},
                  ),
                ),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getProductsByPriceRange(
    String? deviceId,
    double? minPrice,
    double? maxPrice,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByPriceRange, [
              deviceId,
              minPrice,
              maxPrice,
            ]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(
                  this,
                  Invocation.method(#getProductsByPriceRange, [
                    deviceId,
                    minPrice,
                    maxPrice,
                  ]),
                ),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, bool> updateProductStock(
    String? deviceId,
    String? productId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductStock, [
              deviceId,
              productId,
              quantity,
            ]),
            returnValue: _i6.dummyValue<_i3.TaskEither<_i4.Failure, bool>>(
              this,
              Invocation.method(#updateProductStock, [
                deviceId,
                productId,
                quantity,
              ]),
            ),
          )
          as _i3.TaskEither<_i4.Failure, bool>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getRecommendedProducts(
    String? deviceId, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecommendedProducts,
              [deviceId],
              {#limit: limit},
            ),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(
                  this,
                  Invocation.method(
                    #getRecommendedProducts,
                    [deviceId],
                    {#limit: limit},
                  ),
                ),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);

  @override
  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>> getProductsByIds(
    List<String>? productIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByIds, [productIds]),
            returnValue: _i6
                .dummyValue<
                  _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>
                >(this, Invocation.method(#getProductsByIds, [productIds])),
          )
          as _i3.TaskEither<_i4.Failure, List<_i5.ProductModel>>);
}
