// Mocks generated by Mockito 5.4.6 from annotations
// in lunchbox/test/features/cart/providers/cart_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:lunchbox/core/errors/failure.dart' as _i6;
import 'package:lunchbox/features/cart/entities/cart_item_model.dart' as _i3;
import 'package:lunchbox/features/cart/repositories/cart_repository.dart'
    as _i2;
import 'package:lunchbox/features/product/entities/product_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i2.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.CartItemModel> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue: <_i3.CartItemModel>[],
          )
          as List<_i3.CartItemModel>);

  @override
  void setCurrentDeviceId(String? deviceId) => super.noSuchMethod(
    Invocation.method(#setCurrentDeviceId, [deviceId]),
    returnValueForMissingStub: null,
  );

  @override
  void addToCart(_i4.ProductModel? product, {int? quantity = 1}) =>
      super.noSuchMethod(
        Invocation.method(#addToCart, [product], {#quantity: quantity}),
        returnValueForMissingStub: null,
      );

  @override
  void removeFromCart(String? itemId) => super.noSuchMethod(
    Invocation.method(#removeFromCart, [itemId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateCartItemQuantity(String? itemId, int? quantity) =>
      super.noSuchMethod(
        Invocation.method(#updateCartItemQuantity, [itemId, quantity]),
        returnValueForMissingStub: null,
      );

  @override
  void clearCart() => super.noSuchMethod(
    Invocation.method(#clearCart, []),
    returnValueForMissingStub: null,
  );

  @override
  double getCartTotal() =>
      (super.noSuchMethod(
            Invocation.method(#getCartTotal, []),
            returnValue: 0.0,
          )
          as double);

  @override
  int getCartItemCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItemCount, []),
            returnValue: 0,
          )
          as int);

  @override
  bool isCartEmpty() =>
      (super.noSuchMethod(
            Invocation.method(#isCartEmpty, []),
            returnValue: false,
          )
          as bool);

  @override
  bool isInCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#isInCart, [productId]),
            returnValue: false,
          )
          as bool);

  @override
  int getProductQuantityInCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductQuantityInCart, [productId]),
            returnValue: 0,
          )
          as int);

  @override
  _i5.TaskEither<_i6.Failure, bool> syncCart() =>
      (super.noSuchMethod(
            Invocation.method(#syncCart, []),
            returnValue: _i7.dummyValue<_i5.TaskEither<_i6.Failure, bool>>(
              this,
              Invocation.method(#syncCart, []),
            ),
          )
          as _i5.TaskEither<_i6.Failure, bool>);

  @override
  void addMultipleToCart(Map<_i4.ProductModel, int>? productsWithQuantity) =>
      super.noSuchMethod(
        Invocation.method(#addMultipleToCart, [productsWithQuantity]),
        returnValueForMissingStub: null,
      );
}
