// Mocks generated by Mockito 5.4.6 from annotations
// in lunchbox/test/features/cart/providers/cart_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i6;
import 'package:lunchbox/core/errors/failure.dart' as _i7;
import 'package:lunchbox/features/cart/entities/cart_item_model.dart' as _i4;
import 'package:lunchbox/features/cart/repositories/cart_repository.dart'
    as _i2;
import 'package:lunchbox/features/product/entities/product_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i2.CartRepository {
  MockCartRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CartItemModel>> getCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItems, []),
            returnValue: _i3.Future<List<_i4.CartItemModel>>.value(
              <_i4.CartItemModel>[],
            ),
          )
          as _i3.Future<List<_i4.CartItemModel>>);

  @override
  void setCurrentDeviceId(String? deviceId) => super.noSuchMethod(
    Invocation.method(#setCurrentDeviceId, [deviceId]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> addToCart(_i5.ProductModel? product, {int? quantity = 1}) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [product], {#quantity: quantity}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeFromCart(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [itemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateCartItemQuantity(String? itemId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItemQuantity, [itemId, quantity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleItemSelected(String? itemId, bool? isSelected) =>
      (super.noSuchMethod(
            Invocation.method(#toggleItemSelected, [itemId, isSelected]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeItems(List<String>? itemIds) =>
      (super.noSuchMethod(
            Invocation.method(#removeItems, [itemIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<double> getCartTotal() =>
      (super.noSuchMethod(
            Invocation.method(#getCartTotal, []),
            returnValue: _i3.Future<double>.value(0.0),
          )
          as _i3.Future<double>);

  @override
  _i3.Future<int> getCartItemCount() =>
      (super.noSuchMethod(
            Invocation.method(#getCartItemCount, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> isCartEmpty() =>
      (super.noSuchMethod(
            Invocation.method(#isCartEmpty, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> isInCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#isInCart, [productId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getProductQuantityInCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductQuantityInCart, [productId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i6.TaskEither<_i7.Failure, bool> syncCart() =>
      (super.noSuchMethod(
            Invocation.method(#syncCart, []),
            returnValue: _i8.dummyValue<_i6.TaskEither<_i7.Failure, bool>>(
              this,
              Invocation.method(#syncCart, []),
            ),
          )
          as _i6.TaskEither<_i7.Failure, bool>);

  @override
  _i3.Future<void> addMultipleToCart(
    Map<_i5.ProductModel, int>? productsWithQuantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addMultipleToCart, [productsWithQuantity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
