// Mocks generated by Mockito 5.4.6 from annotations
// in lunchbox/test/features/cart/repositories/cart_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lunchbox/core/services/storage_service.dart' as _i3;
import 'package:lunchbox/features/auth/models/user_model.dart' as _i11;
import 'package:lunchbox/features/city/entities/city_model.dart' as _i7;
import 'package:lunchbox/features/device/entities/device_model.dart' as _i8;
import 'package:lunchbox/features/order/entities/order_model.dart' as _i10;
import 'package:lunchbox/features/product/entities/product_model.dart' as _i9;
import 'package:lunchbox/shared/models/api_response_model.dart' as _i2;
import 'package:lunchbox/shared/services/api_provider.dart' as _i5;
import 'package:lunchbox/shared/services/mock_provider.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponseModel_0<T1> extends _i1.SmartFake
    implements _i2.ApiResponseModel<T1> {
  _FakeApiResponseModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i3.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T? read<T>(String? key) =>
      (super.noSuchMethod(Invocation.method(#read, [key])) as T?);

  @override
  _i4.Future<void> write(String? key, Object? value) =>
      (super.noSuchMethod(
            Invocation.method(#write, [key, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool hasKey(String? key) =>
      (super.noSuchMethod(Invocation.method(#hasKey, [key]), returnValue: false)
          as bool);

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  int getSize() =>
      (super.noSuchMethod(Invocation.method(#getSize, []), returnValue: 0)
          as int);
}

/// A class which mocks [ApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiProvider extends _i1.Mock implements _i5.ApiProvider {
  MockApiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponseModel<T>> get<T>(
    String? path,
    T Function(Object?)? fromJsonT, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path, fromJsonT],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i2.ApiResponseModel<T>>.value(
              _FakeApiResponseModel_0<T>(
                this,
                Invocation.method(
                  #get,
                  [path, fromJsonT],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<T>>);

  @override
  _i4.Future<_i2.ApiResponseModel<T>> post<T>(
    String? path,
    Object? data,
    T Function(Object?)? fromJsonT, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path, data, fromJsonT],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i2.ApiResponseModel<T>>.value(
              _FakeApiResponseModel_0<T>(
                this,
                Invocation.method(
                  #post,
                  [path, data, fromJsonT],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<T>>);

  @override
  _i4.Future<_i2.ApiResponseModel<T>> put<T>(
    String? path,
    Object? data,
    T Function(Map<String, dynamic>)? fromJsonT, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path, data, fromJsonT],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i2.ApiResponseModel<T>>.value(
              _FakeApiResponseModel_0<T>(
                this,
                Invocation.method(
                  #put,
                  [path, data, fromJsonT],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<T>>);

  @override
  _i4.Future<_i2.ApiResponseModel<T>> delete<T>(
    String? path,
    T Function(Map<String, dynamic>)? fromJsonT, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path, fromJsonT],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i2.ApiResponseModel<T>>.value(
              _FakeApiResponseModel_0<T>(
                this,
                Invocation.method(
                  #delete,
                  [path, fromJsonT],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<T>>);

  @override
  _i4.Future<_i2.ApiResponseModel<T>> uploadFile<T>(
    String? path,
    String? filePath,
    String? fileName,
    T Function(Object?)? fromJsonT, {
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [path, filePath, fileName, fromJsonT],
              {#data: data},
            ),
            returnValue: _i4.Future<_i2.ApiResponseModel<T>>.value(
              _FakeApiResponseModel_0<T>(
                this,
                Invocation.method(
                  #uploadFile,
                  [path, filePath, fileName, fromJsonT],
                  {#data: data},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<T>>);
}

/// A class which mocks [MockProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockProvider extends _i1.Mock implements _i6.MockProvider {
  MockMockProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponseModel<List<_i7.CityModel>>> getCities() =>
      (super.noSuchMethod(
            Invocation.method(#getCities, []),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<List<_i7.CityModel>>>.value(
                  _FakeApiResponseModel_0<List<_i7.CityModel>>(
                    this,
                    Invocation.method(#getCities, []),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<List<_i7.CityModel>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<List<_i8.DeviceModel>>> getDevices({
    String? cityId,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDevices, [], {
              #cityId: cityId,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<List<_i8.DeviceModel>>>.value(
                  _FakeApiResponseModel_0<List<_i8.DeviceModel>>(
                    this,
                    Invocation.method(#getDevices, [], {
                      #cityId: cityId,
                      #latitude: latitude,
                      #longitude: longitude,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<List<_i8.DeviceModel>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>> getDeviceDetail(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceDetail, [deviceId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>>.value(
                  _FakeApiResponseModel_0<_i8.DeviceModel>(
                    this,
                    Invocation.method(#getDeviceDetail, [deviceId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>> getDeviceById(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceById, [deviceId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>>.value(
                  _FakeApiResponseModel_0<_i8.DeviceModel>(
                    this,
                    Invocation.method(#getDeviceById, [deviceId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i8.DeviceModel>>);

  @override
  List<_i9.ProductModel> generateMockProducts(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#generateMockProducts, [count]),
            returnValue: <_i9.ProductModel>[],
          )
          as List<_i9.ProductModel>);

  @override
  _i4.Future<_i2.ApiResponseModel<List<_i9.ProductModel>>>
  getProductsByDeviceId(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByDeviceId, [deviceId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<List<_i9.ProductModel>>>.value(
                  _FakeApiResponseModel_0<List<_i9.ProductModel>>(
                    this,
                    Invocation.method(#getProductsByDeviceId, [deviceId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<List<_i9.ProductModel>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i9.ProductModel>> getProductById(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<_i9.ProductModel>>.value(
                  _FakeApiResponseModel_0<_i9.ProductModel>(
                    this,
                    Invocation.method(#getProductById, [productId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i9.ProductModel>>);

  @override
  _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>> getOrders(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrders, [userId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>>.value(
                  _FakeApiResponseModel_0<List<_i10.OrderModel>>(
                    this,
                    Invocation.method(#getOrders, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i11.UserModel>> getUserInfo(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, [userId]),
            returnValue: _i4.Future<_i2.ApiResponseModel<_i11.UserModel>>.value(
              _FakeApiResponseModel_0<_i11.UserModel>(
                this,
                Invocation.method(#getUserInfo, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i11.UserModel>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>> createOrder(
    String? userId,
    String? deviceId,
    List<Map<String, dynamic>>? cartItems,
    _i10.PaymentMethod? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createOrder, [
              userId,
              deviceId,
              cartItems,
              paymentMethod,
            ]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>>.value(
                  _FakeApiResponseModel_0<_i10.OrderModel>(
                    this,
                    Invocation.method(#createOrder, [
                      userId,
                      deviceId,
                      cartItems,
                      paymentMethod,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>>);

  @override
  _i4.Future<_i2.ApiResponseModel<Map<String, dynamic>>> login(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [data]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<Map<String, dynamic>>>.value(
                  _FakeApiResponseModel_0<Map<String, dynamic>>(
                    this,
                    Invocation.method(#login, [data]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i11.UserModel>> register(
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [data]),
            returnValue: _i4.Future<_i2.ApiResponseModel<_i11.UserModel>>.value(
              _FakeApiResponseModel_0<_i11.UserModel>(
                this,
                Invocation.method(#register, [data]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i11.UserModel>>);

  @override
  _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>> getUserOrders(
    Map<String, dynamic>? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOrders, [params]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>>.value(
                  _FakeApiResponseModel_0<List<_i10.OrderModel>>(
                    this,
                    Invocation.method(#getUserOrders, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<List<_i10.OrderModel>>>);

  @override
  _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>> getOrderById(
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrderById, [orderId]),
            returnValue:
                _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>>.value(
                  _FakeApiResponseModel_0<_i10.OrderModel>(
                    this,
                    Invocation.method(#getOrderById, [orderId]),
                  ),
                ),
          )
          as _i4.Future<_i2.ApiResponseModel<_i10.OrderModel>>);
}
